# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "vyos/equuleus"
  config.vm.box_version = "1.3.0"

  # virtualbox specifics
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vyos"
    vb.cpus = 1
    vb.memory = "1024"
  end

  # SSH settings
  config.ssh.username = "vyos"
  config.ssh.password = "vyos"
  config.ssh.insert_key = false

  # Disable rsync (has issues with windows)
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Load prebaked vyos settings
  config.vm.provision "file", source: "./files/config.sh", destination: "/home/vyos/config.sh"
  config.vm.provision "shell", inline: <<-SHELL
    #!/bin/vbash
    source /opt/vyatta/etc/functions/script-template
    configure
    . /home/vyos/config.sh
    commit
    save
    exit
    rm /home/vyos/config.sh
    sudo shutdown now
  SHELL
end
