# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "lubuntu-desktop-22.04-v2"
  config.vm.box_url = "../boxes/lubuntu-desktop-22.04-v2.box"

  # virtualbox specifics
  config.vm.provider "virtualbox" do |vb|
    vb.name = "pc1"
    vb.cpus = 2
    vb.memory = "2048"

    # Put it in a VirtualBox group
    vb.customize ["modifyvm", :id, "--groups", "/Capstone"]

    # set the network adapters
    # vagrant needs one of them to be nat with port forwarding
    vb.customize ["modifyvm", :id, "--nic1", "intnet", "--intnet1", "intnet-1"]
    vb.customize ["modifyvm", :id, "--nic2", "nat"]
    vb.customize ["modifyvm", :id, "--natpf2" , "guestssh,tcp,,21901,,22"]
  end

  config.vm.hostname = "acmepc1"

  config.vm.provision "shell", inline: <<-SHELL
    echo '192.168.20.100  intranet' >> /etc/hosts
    echo '192.168.20.100  intranet.acme.local' >> /etc/hosts
    echo '192.168.10.1  router' >> /etc/hosts
  SHELL

  # Create users
  config.vm.provision "shell", path: "./files/create-users.sh"

  # Set up Moe's ssh keys, reuse our shared key
  config.vm.provision "file", source: "../keys/id_rsa", destination: "~vagrant/moe_id_rsa"
  config.vm.provision "file", source: "../keys/id_rsa.pub", destination: "~vagrant/moe_id_rsa.pub"
  config.vm.provision "shell", inline: <<-SHELL
    mkdir ~moe/.ssh 
    cp ~vagrant/moe_id_rsa ~moe/.ssh/id_rsa
    cp ~vagrant/moe_id_rsa.pub ~moe/.ssh/id_rsa.pub
    chown -R moe:moe ~moe
    chmod 600 ~moe/.ssh/id_rsa
  SHELL

  # only the acme user should be able to graphically login
  config.vm.provision "shell", path: "./files/acme-login.sh"

  # bash histories
  config.vm.provision "shell", inline: <<-SHELL
    cp /vagrant/files/triddle.bash.history ~triddle/.bash_history
    chown triddle:triddle ~triddle/.bash_history
    cp /vagrant/files/amac.bash.history ~amac/.bash_history
    chown amac:amac ~amac/.bash_history
    cp /vagrant/files/moe.bash.history ~moe/.bash_history
    chown moe:moe ~moe/.bash_history
    cp /vagrant/files/root.bash.history /root/.bash_history
  SHELL

  # here come the apt installs, so do an update once
  config.vm.provision "shell", inline: "apt update"

  # install standard tools
  config.vm.provision "shell", inline: "apt install -y curl net-tools vim"

  # install samba server
  config.vm.provision "shell", inline: "apt install -y samba"

  # configure samba server
  config.vm.provision "shell", inline: <<-SHELL
    cat /vagrant/files/smb-add.conf >> /etc/samba/smb.conf
    # create acmecompany test file
    systemctl restart smbd
  SHELL

  # upload teardown script to be run outside of Vagrant
  config.vm.provision "file", source: "./files/teardown.sh", destination: "~/teardown.sh"

  # Allow temporary root ssh access so teardown script can remove vagrant user
  config.vm.provision "file", source: "../keys/id_rsa.pub", destination: "~/id_rsa.pub"
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /root/.ssh
    cp ~vagrant/id_rsa.pub /root/.ssh/authorized_keys
  SHELL
end
