# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  # virtualbox specifics
  config.vm.provider "virtualbox" do |vb|
    vb.name = "soc"
    vb.cpus = 2
    vb.memory = "2048"

    # Put it in a VirtualBox group
    vb.customize ["modifyvm", :id, "--groups", "/Capstone"]

    # set the network adapters
    # vagrant needs one of them to be nat with port forwarding
    vb.customize ["modifyvm", :id, "--nic1", "intnet", "--intnet1", "intnet-3"]
    vb.customize ["modifyvm", :id, "--nic2", "nat"]
    vb.customize ["modifyvm", :id, "--natpf2" , "guestssh,tcp,,21904,,22"]
  end

  config.vm.hostname = "RoadRunner"

  #these look a little wonky but just copying for now
  config.vm.provision "shell", inline: <<-SHELL
    echo '192.168.20.100  acmedmz.acmecompany.fis' >> /etc/hosts
    echo '192.168.20.100  intranet.acmecompany.fis' >> /etc/hosts
  SHELL

  # Create ip addresses
  #config.vm.provision "shell", path: "./files/create-ips.sh"

  # Create users
  config.vm.provision "shell", path: "./files/create-users.sh"

  # here come the apt installs, so do an update once
  config.vm.provision "shell", inline: "apt update"

  # install standard tools
  config.vm.provision "shell", inline: "apt install -y curl net-tools vim"

  # upload teardown script to be run outside of Vagrant
  config.vm.provision "file", source: "./files/teardown.sh", destination: "~/teardown.sh"

  # Allow temporary root ssh access so teardown script can remove vagrant user
  config.vm.provision "file", source: "../keys/id_rsa.pub", destination: "~/id_rsa.pub"
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /root/.ssh
    cp ~vagrant/id_rsa.pub /root/.ssh/authorized_keys
  SHELL
end
